name: null
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - r-base
  - r-essentials
  - r-tidyverse
  - r-netcdf4
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - netcdf4
  prefix: .conda_env
